### ISSUE TITLE
Improvements for the German language

### ISSUE THREAD

**Issue by Partymann2000** [WemxPro/languages#6]
**client.php**
- Change from `'price_block_desc' => 'Erst pro :period :symbol:total_price danach :symbol:renewal_price pro :per_period',` to `'price_block_desc' => ':total_price:symbol im ersten :period, danach :renewal_price:symbol :per_period',` as this sounds better and is also grammatically better

**Comment by GIGABAIT93** [comment]
you can make a commit yourself and we will confirm it is a public repository
