### ISSUE TITLE
BR language some errors that I think it's not related to my translation .

### ISSUE THREAD

**Issue by VozDeOuro** [WemxPro/languages#8]
hey @Mubeen142
![265791562-61b6ccdf-6fd7-42f2-93c7-3c9fd32be4c7](https://github.com/WemxPro/languages/assets/36045463/05c065e2-5909-4938-ab0e-eeceb84530d2)
this panel name is wrong
it's not telling
“Brazilian Portuguese” or just Brazil if you want to go with countries

another error that i found is that here it's not showing the month and days right
i don't even know what that means "sizhun 'zo" or "Eos" on date
![265791853-93f91fac-4b87-4d35-a426-eafc945713b5](https://github.com/WemxPro/languages/assets/36045463/963886d5-a2b0-4492-bfce-d2d567f13c7b)

if that placeholder, is a miss translation on my part pls tell me

**Comment by GIGABAIT93** [comment]
fix

**Comment by VozDeOuro** [comment]
:)
